# Generated by Django 5.0.7 on 2024-07-28 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Literal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_negative', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_defeasible', models.BooleanField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion', to='aspic_generator.literal')),
                ('premises', models.ManyToManyField(related_name='premises', to='aspic_generator.literal')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sub_arguments', models.ManyToManyField(blank=True, to='aspic_generator.argument')),
                ('top_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_rule', to='aspic_generator.rule')),
            ],
        ),
    ]
